# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrPlus < Formula
  desc "herdr-plus — an add-on platform for the herdr terminal multiplexer."
  homepage "https://github.com/cloudmanic/herdr-plus"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.8/herdr-plus_0.0.8_darwin_amd64.tar.gz"
      sha256 "6ac9aa31f02f1d1393d92c09d89bb11cd4dc5ac20591726e0851817704b39b2a"

      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.8/herdr-plus_0.0.8_darwin_arm64.tar.gz"
      sha256 "a77974a98e04ae842cd04071c6a5f7a5ec9b2198869c16f853988cad38dae4e7"

      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.8/herdr-plus_0.0.8_linux_amd64.tar.gz"
      sha256 "b1095c5a711586b2678b234a81607c98fb9a490e97bdd2f1b5bd19e57fd15225"
      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.8/herdr-plus_0.0.8_linux_arm64.tar.gz"
      sha256 "551492981fa4af844041a6570a616b84644d2d4a5076a276a759fee9c397408d"
      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
  end

  test do
    assert_path_exists bin/"herdr-plus"
  end
end
