# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrPlus < Formula
  desc "herdr-plus — an extension for the herdr terminal multiplexer."
  homepage "https://github.com/cloudmanic/herdr-plus"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.1.22/herdr-plus_0.1.22_darwin_amd64.tar.gz"
      sha256 "2a5a3f3800f0438933400f3b69bfa10eb7e281571ee5795cd4e823b0a2668d1f"

      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.1.22/herdr-plus_0.1.22_darwin_arm64.tar.gz"
      sha256 "5de0a036ff6e09fc5bcea43af18cfabed8b02d683a9dfe0c0e3736143081743f"

      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.1.22/herdr-plus_0.1.22_linux_amd64.tar.gz"
      sha256 "d16e20862991335af4d8f83661844246db7072f6ce6d94fd3b5de932d44de407"
      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.1.22/herdr-plus_0.1.22_linux_arm64.tar.gz"
      sha256 "648c3fb86b7630c449481d13306d627fab5f8fe07c67cc691d3708ac8cf13c37"
      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
  end

  test do
    assert_path_exists bin/"herdr-plus"
  end
end
