# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrPlus < Formula
  desc "herdr-plus — an add-on platform for the herdr terminal multiplexer."
  homepage "https://github.com/cloudmanic/herdr-plus"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.5/herdr-plus_0.0.5_darwin_amd64.tar.gz"
      sha256 "41dbb898877e35c2adbcbdcb17c94e553e72336d9d995b4d8a206cd598c7dd26"

      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.5/herdr-plus_0.0.5_darwin_arm64.tar.gz"
      sha256 "739495772ab48fc3e32ca3a498eb274a7334941c4048ae9fe6d8b3e2bc1651f7"

      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.5/herdr-plus_0.0.5_linux_amd64.tar.gz"
      sha256 "d4cfd819daa57909399caddc0924a563fa2e225760343c0eadbd81f1ec8aba96"
      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/herdr-plus/releases/download/v0.0.5/herdr-plus_0.0.5_linux_arm64.tar.gz"
      sha256 "eef6ae91195bfe74567429d21671216057352075e28ff9dacf9c9e3a6f5b0c87"
      define_method(:install) do
        bin.install "herdr-plus"
      end
    end
  end

  test do
    assert_path_exists bin/"herdr-plus"
  end
end
